### PR TITLE
Re-adding the jupyterjub service

### PR DESCRIPTION
**Pull request by JPchico**
Re-adding the jupyterhub service so that it can properly start. . Addresses #36

### CODE REVIEW

**Comment by ltalirz** [comment]
Thanks @JPchico for the fix!

**Comment by JPchico** [comment]
No problem @ltalirz !

There seems to be an issue that is the same that is popping up in the [`pre-commit` PR](https://github.com/aiidalab/ansible-role-aiidalab-server/pull/35)

```
internal-error the role 'geerlingguy.docker' was not found in ansible.legacy:/home/runner/work/ansible-role-aiidalab-server/ansible-role-aiidalab-server/molecule/default/roles:/home/runner/.cache/ansible-compat/9c3b41/roles:/home/runner/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/runner/work/ansible-role-aiidalab-server:/home/runner/work/ansible-role-aiidalab-server/ansible-role-aiidalab-server/molecule/default
```

It seems to be an error from the other role, no clue why that is failing though.

**Review by ltalirz — COMMENTED** [review]
Thanks - yeah, I had a quick go at fixing it but didn't manage.

Merging your contribution now; will try to get CI working in https://github.com/aiidalab/ansible-role-aiidalab-server/pull/38

Now that I look into it, it appears to me that molecule actually never ran successfully on CI since @yakutovicha migrated to Github actions.

**Comment by yakutovicha** [comment]
> Now that I look into it, it appears to me that molecule actually never ran successfully on CI since @yakutovicha migrated to Github actions.

I managed to fix the tests in #30, but then it stopped working again.

**Pull request merged**
