### PR TITLE
Fix molecule test.

### LINKED ISSUE #29: CI: pull docker image results in "no space left on device" error.
When running tests locally or on GitHub, I get the following error:

```
TASK [marvel_nccr.aiidalab_server : Pull the docker image aiidalab/aiidalab-docker-stack:latest.] ***
fatal: [instance]: FAILED! => {"changed": false, "msg": "Error pulling aiidalab/aiidalab-docker-stack - code: None message: failed to register layer: ApplyLayer exit status 1 stdout:  stderr: write /opt/conda/lib/python3.7/site-packages/plotly/validators/__pycache__/_isosurface.cpython-37.pyc: no space left on device"}
```

It looks to me that this is not related to the free space on the disc. I do have enough space on my laptop, but I am still getting the same error.

### PR DESCRIPTION
**Pull request by yakutovicha**
fixes #29

### CODE REVIEW

**Review by csadorf — COMMENTED** [review]
What happens if this is not run on GitHub actions?

**Comment by yakutovicha** [comment]
> What happens if this is not run on GitHub actions?

The tests will fail with the same error as in issue #29.

To avoid failure one needs to apply the change from this PR to their docker configuration.

**Comment by csadorf** [comment]
> > What happens if this is not run on GitHub actions?
> 
> The tests will fail with the same error as in issue #29.
> 
> To avoid failure one needs to apply the change from this PR to their docker configuration.

Who is "their" in this context? Either way this is tentatively approved, but I do not have enough context to fully evaluate this.

**Comment by yakutovicha** [comment]
> Who is "their" in this context? Either way this is tentatively approved, but I do not have enough context to fully evaluate this.

Anyone who runs the test. For example, if you want to run the test on your machine, you need to apply the same modification as in this PR.
```
echo '{"cgroup-parent":"/actions_job","storage-driver":"vfs"}' | sudo tee /etc/docker/daemon.json
```

**Comment by yakutovicha** [comment]
I will go ahead with merging then, I guess.

**Comment by csadorf** [comment]
> > Who is "their" in this context? Either way this is tentatively approved, but I do not have enough context to fully evaluate this.
> 
> Anyone who runs the test. For example, if you want to run the test on your machine, you need to apply the same modification as in this PR.
> 
> ```
> echo '{"cgroup-parent":"/actions_job","storage-driver":"vfs"}' | sudo tee /etc/docker/daemon.json
> ```

Thanks, that clears it up!

**Comment by csadorf** [comment]
> I will go ahead with merging then, I guess.

Yes – just to clarify – did you expect anything else from me here?

**Comment by yakutovicha** [comment]
> > I will go ahead with merging then, I guess.
> 
> Yes – just to clarify – did you expect anything else from me here?

I think no. I was just not sure what the "tentative approval" implies. So my best guess was to go ahead.

**Pull request merged**
